
[package]
name = "test_utils"
version = "0.1.0"
authors = ["Natalia Margolis <natalia.margolis@mapbox.com>"]

[dependencies]
tempfile = "3.0"
carmen-core = { path = "../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
failure = "0.1.5"
