[package]
name = "carmen-cache-sys"
version = "0.1.0"
authors = ["Andrew Pendleton <andrew@mapbox.com>"]
edition = "2018"

[build-dependencies]
librocksdb-sys = "5.17"
cpp_build = "0.5"

[dependencies]
cpp = "0.5"

[lib]
name = "carmen_cache_sys"
path = "lib.rs"
